// Active OPD Update controller moved from opd_update.html inline code
// v117.4.12

document.addEventListener("DOMContentLoaded",()=>{
 const isOPD=true;let selected=null;
 const clearLoadedState=()=>{selected=null;$('patients').innerHTML="";$('edit').hidden=true;$('confirmation').hidden=true;$('confirmation').innerHTML="";$('status').textContent="";$('loadStatus').hidden=true;$('saveStatus').hidden=true;$('saveStatus').textContent="";};
 const setLoadBusy=(busy)=>{$('load').disabled=busy;$('load').textContent=busy?"Loading...":"Load";$('load').classList.toggle("opd-loading-btn",busy);};
 const setSaveBusy=(busy)=>{$('save').disabled=busy;$('save').textContent=busy?"Updating...":"Update OPD Details";$('save').classList.toggle("opd-updating-btn",busy);};
 const paymentMode=()=>{const c=Number($('cash').dataset.actual||0),o=Number($('online').dataset.actual||0);if(c>0&&o>0)return "Split";if(o>0)return "Online";return "Cash";};
 const refreshPaymentUI=()=>{const mode=paymentMode();const c=Number($('cash').value)||0,o=Number($('online').value)||0;$('chargeField').hidden=mode==="Split";$('splitCashField').hidden=mode!=="Split";$('splitOnlineField').hidden=mode!=="Split";$('splitTotalField').hidden=mode!=="Split";$('chargeLabel').textContent=mode==="Cash"?"OPD Charges Paid in Cash":mode==="Online"?"OPD Charges Paid Online":"OPD Charges Paid in Split";if(mode==="Split")$('totalPaid').textContent=(c+o).toFixed(2).replace(/\.00$/,'');};
 const renderPatient=(x,b)=>{selected=x;document.querySelectorAll('.patient-option').forEach(z=>z.classList.remove('selected'));b.classList.add('selected');$('edit').hidden=false;$('confirmation').hidden=true;$('confirmation').innerHTML="";$('name').value=x.name||"";$('age').value=x.age??"";$('unit').value=x.ageUnit||"years";$('address').value=x.address||"";$('ref').value=x.referredBy||"";$('editWa').value=x.whatsapp||"";$('nextFollowupCity').innerHTML=NEURON_CONFIG.cities.map(c=>`<option value="${U.esc(c)}">${U.esc(c)}</option>`).join("");const followupCity=String(x.nextFollowupCity||"").trim();const cityExists=[...$('nextFollowupCity').options].some(o=>o.value===followupCity);$('nextFollowupCity').value=cityExists?followupCity:"";$('charge').value=Number(x.totalOPDCharges||0);$('cash').value=Number(x.opdCashPaid||0);$('online').value=Number(x.opdOnlinePaid||0);$('cash').dataset.actual=String(x.opdCashPaid??0);$('online').dataset.actual=String(x.opdOnlinePaid??0);refreshPaymentUI();};
 $('city').innerHTML=NEURON_CONFIG.cities.map(x=>`<option>${U.esc(x)}</option>`).join("");
 const scheduledCity=window.Schedule?.cityAtNow?.(NEURON_CONFIG.cities)||"Latur";
 if(NEURON_CONFIG.cities.includes(scheduledCity)) $("city").value=scheduledCity;
 $('city').addEventListener("change",()=>{clearLoadedState();});
 $('load').onclick=async()=>{clearLoadedState();setLoadBusy(true);$('loadStatus').hidden=false;$('loadStatus').className="status opd-loading";$('loadStatus').textContent="Wait we are Loading Today's OPD details from system...";try{const r=await NeuronAPI.call("getTodayOPDPatientsByWhatsApp",{whatsapp:U.phone($('wa').value),city:$('city').value});const patients=[...(r.patients||[])].sort((a,b)=>{const at=Date.parse(a.bookingTimestamp||"");const bt=Date.parse(b.bookingTimestamp||"");if(Number.isFinite(at)&&Number.isFinite(bt)&&bt!==at)return bt-at;if(Number.isFinite(at)!==Number.isFinite(bt))return Number.isFinite(bt)?1:-1;return 0;});patients.forEach((x)=>{const b=document.createElement('button');b.className='patient-option';b.innerHTML=`<b>${U.esc(x.name)}</b><small>${x.age} ${U.esc(x.ageUnit)} • ${U.date(x.date)}</small>`;b.onclick=()=>renderPatient(x,b);$('patients').appendChild(b);});if(r.patients.length===1)renderPatient(r.patients[0],$('patients').firstElementChild);else if(!r.patients.length)$('status').textContent="No today's OPD patient found.";}catch(e){$('status').textContent=e.message||"Unable to load OPD details."}finally{setLoadBusy(false);$('loadStatus').hidden=true;}};
 $('save').onclick=async()=>{if(!selected)return;setSaveBusy(true);$('saveStatus').hidden=false;$('saveStatus').className="status opd-loading";$('saveStatus').textContent="Wait we are updating OPD details to system...";const mode=paymentMode(),charge=mode==="Cash"?Number($('charge').value)||0:mode==="Online"?Number($('charge').value)||0:(Number($('cash').value)||0)+(Number($('online').value)||0);const id=U.uuid("upd"),p={updateRequestId:id,appointmentId:selected.appointmentId,city:selected.city,whatsapp:selected.whatsapp,whatsappNew:U.phone($('editWa').value),name:U.title($('name').value),age:Number($('age').value),ageUnit:$('unit').value,address:U.title($('address').value),referredBy:U.title($('ref').value),nextFollowupCity:$('nextFollowupCity').value,opdCharges:charge,opdPaymentMode:mode,opdCashPaid:mode==="Online"?0:mode==="Cash"?charge:Number($('cash').value)||0,opdOnlinePaid:mode==="Cash"?0:mode==="Online"?charge:Number($('online').value)||0};try{await IDB.put("tx",{id,type:"OPD_UPDATE",status:"pending",payload:p});const r=await NeuronAPI.call("updateOPDDetails",p,25000);await IDB.put("tx",{id,type:"OPD_UPDATE",status:"complete",payload:p,result:r});const before=r.before||{},after=r.after||{};const fields=[['Patient Name',before.name,after.name],['Age',`${before.age} ${before.ageUnit}`,`${after.age} ${after.ageUnit}`],['Address',before.address,after.address],['Referred By Dr./Hospital',before.referredBy,after.referredBy],['WhatsApp Number',before.whatsapp,after.whatsapp],['Next Follow-up City',before.nextFollowupCity,after.nextFollowupCity],['OPD Charges Paid',before.opdTotalPaid,after.opdTotalPaid],['Paid in Cash',before.opdCashPaid,after.opdCashPaid],['Paid Online',before.opdOnlinePaid,after.opdOnlinePaid]];const changed=fields.filter(f=>String(f[1]??"")!==String(f[2]??""));$('confirmation').hidden=false;$('confirmation').innerHTML=`<div class="success"><div class="success-icon">✓</div><h2>OPD Details Updated</h2><p>Appointment ID: <b>${U.esc(r.appointmentId)}</b></p>${changed.length?`<p><b>Changed and updated:</b></p><ul class="changed-list">${changed.map(f=>`<li><b>${U.esc(f[0])}</b>: ${U.esc(String(f[1]??""))} → <b>${U.esc(String(f[2]??""))}</b></li>`).join('')}</ul>`:`<p>No values were changed.</p>`}</div>`;}catch(e){await IDB.put("tx",{id,type:"OPD_UPDATE",status:"uncertain",payload:p}).catch(()=>{});alert(e.message||"Update status is uncertain. Do not repeat it until the original request is checked.");}finally{setSaveBusy(false);$('saveStatus').hidden=true;}};
});
